production: true
destination: ../_site
exclude: [publish.sh, syelle.github.com.sublime-project, syelle.github.com.sublime-workspace]

permalink: /blog/:year/:month/:day/:title

name: Min-Maxing
tagline: Experiments in optimizing web pages, business processes, and life in general.
description: Experiments in optimizing web pages, business processes, and life in general.

url: http://www.min-maxing.com
tag_dir: /blog/tag/

paginate_path: "blog/page-:num"
paginate: 4

navigation:
- text: Blog
  url: /blog/
  layout: blog
- text: About
  url: /about/
  layout: about
- text: Email Me
  url: mailto:syelle@gmail.com
  layout: external-link
