auto: true
production: true
destination: ../_site
exclude: [publish.sh]

permalink: /blog/:year/:month/:day/:title

name: Min-Maxing
tagline: Experiments in optimizing web pages, business processes, and life in general.
description: Experiments in optimizing web pages, business processes, and life in general.

url: http://min-maxing.com
tag_dir: /blog/tag/

navigation:
- text: Blog
  url: /blog/
  layout: blog
